version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo "Installing Zipcho Dev Chat Dependencies .... "
      - pip3 install -r requirements.txt

artifacts:
  files:
    - '**/*'
    - appspec.yml