# Generated by Django 3.1.3 on 2022-07-06 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zipchoAdmin', '0002_category_gender_language_talent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='talent',
        ),
    ]
