# Generated by Django 3.1.3 on 2022-07-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20220705_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emailVerified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='mobileNumberVerified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='termsAgreed',
            field=models.BooleanField(default=False),
        ),
    ]
