# Generated by Django 3.1.3 on 2022-07-07 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zipchoAdmin', '0004_country'),
        ('authentication', '0008_auto_20220706_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='languagePreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zipchoAdmin.language')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
