# Generated by Django 3.1.3 on 2022-07-08 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zipchoAdmin', '0004_country'),
        ('authentication', '0010_auto_20220707_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='zipchoAdmin.country'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='zipchoAdmin.gender'),
        ),
    ]
