# Generated by Django 3.1.3 on 2022-08-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_auto_20220809_0544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='usercategory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userinterest',
            name='interest',
        ),
        migrations.RemoveField(
            model_name='userinterest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usertalent',
            name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='languagePreference',
        ),
        migrations.DeleteModel(
            name='userCategory',
        ),
        migrations.DeleteModel(
            name='userInterest',
        ),
        migrations.DeleteModel(
            name='userTalent',
        ),
    ]
